# Generated by Django 4.0.4 on 2022-05-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('Name', models.CharField(max_length=25)),
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Gpa', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Email', models.CharField(max_length=25)),
                ('Mobile', models.CharField(max_length=12)),
                ('Level', models.IntegerField()),
                ('Date', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('Department', models.CharField(choices=[('Cs', 'Cs'), ('Is', 'Is'), ('Ai', 'Ai'), ('It', 'It'), ('Ds', 'Ds')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
