# Generated by Django 4.0.4 on 2022-05-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Addstudent',
        ),
    ]
