# Generated by Django 4.0.4 on 2022-05-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_delete_addstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='mail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='gander',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='gpa',
            new_name='Gpa',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='level',
            new_name='Level',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='mobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='status',
            new_name='Status',
        ),
    ]
