# Generated by Django 4.0.4 on 2022-05-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_date_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='Department',
            field=models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('AI', 'AI'), ('IT', 'IT'), ('DS', 'DS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='add',
            name='Email',
            field=models.EmailField(max_length=25),
        ),
    ]
