# Generated by Django 4.0.4 on 2022-05-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_add_department_alter_add_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
