# Generated by Django 4.0.4 on 2022-05-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='Department',
            field=models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('AI', 'AI'), ('IT', 'IT'), ('DS', 'DS'), ('General', 'General')], max_length=50),
        ),
    ]
