# Generated by Django 4.0.4 on 2022-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_add_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='Date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
